devices/urls.py
from django.urls import path, re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'devices'

urlpatterns=[
    path('', views.home_view, name='home'),
    re_path(r'^profile/(\d+)', views.profile, name="profile"),
    path('records/', views.MaintenanceRecordListView.as_view(), name='maintenance_record_list'),
    path('records/<int:pk>/', views.MaintenanceRecordDetailView.as_view(), name='maintenance_record_detail'),
    path('documentation/', views.DocumentationRecordListView.as_view(), name='documentation_record_list'),
    path('documentation/<int:pk>/', views.DocumentationRecordDetailView.as_view(), name='documentation_record_detail'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

maintain_it/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views
from django_registration.backends.one_step.views import RegistrationView

urlpatterns = [
    path('accounts/register/',
            RegistrationView.as_view(success_url='/'),
            name='django_registration_register'),
    path('accounts/', include('django_registration.backends.one_step.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('logout', views.LogoutView.as_view(), {"next_page": '/'}),
    path('admin/', admin.site.urls),
    path('',include('devices.urls')),
    
    
]

devices/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone
from django.utils.html import escape, linebreaks, urlize
from django.conf import settings
from django.core.exceptions import ValidationError

from markupfield_helpers.helpers import MarkupField


STATUS_CHOICES = [
    ('Complete', 'Complete'),
    ('In Progress', 'In Progress'),
    ('Failed', 'Failed'),
]

# Create your models here.
class Profile(models.Model):
    '''	
    Class to define a user's profile
    '''
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to="profile-pic/", blank=True, default='/profile-pic/default-no-profile-pic.jpg')

    def __str__(self):

        return self.user.username

    @classmethod
    def get_profiles(cls):

        profiles = Profile.objects.all()

        return profiles

    @classmethod
    def get_other_profiles(cls,user_id):


        profiles = Profile.objects.all()

        other_profiles = []

        for profile in profiles:

            if profile.user.id != user_id:

                other_profiles.append(profile)

        return other_profiles


# Create Profile when creating a User
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

# Save Profile when saving a User
@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

class Hardware(models.Model):

    name = models.CharField(
        max_length=255,
        help_text="Enter the type of hardware.",
        unique=True,
    )

    class Meta:
        ordering = ['name']
        verbose_name_plural = 'hardware'

    def __str__(self):
        return self.name


class DocumentationRecord(models.Model):

    title = models.CharField(
        max_length=255,
        help_text="Enter a brief, descriptive title for this documentation.",
        unique=True,
    )

    maintenance_type = models.ForeignKey(
        'MaintenanceType',
        help_text='Select/Create a maintenance type.',
        on_delete=models.PROTECT,
    )

    documentation = MarkupField(
        blank=True,
        help_text='Document how to perform a task.',
        null=True,
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['title']

    def __str__(self):
        return self.title



class MaintenanceRecord(models.Model):
    system = models.ForeignKey(
        'System',
        help_text='Select/Create a system.',
        on_delete=models.PROTECT,
    )

    sys_admin = models.ForeignKey(
        'SysAdmin',
        help_text='Select a system administrator.',
        on_delete=models.PROTECT,
    )

    maintenance_type = models.ForeignKey(
        'MaintenanceType',
        help_text='Select/Create a maintenance type.',
        on_delete=models.PROTECT,
    )

    hardware = models.ManyToManyField(
        'Hardware',
        blank=True,
        help_text='Select the hardware involved in the system maintenance.',
    )

    software = models.ManyToManyField(
        'Software',
        blank=True,
        help_text='Select the software involved in the system maintenance.',
    )

    description = MarkupField(
        blank=True,
        help_text='Enter a description of the system maintenance performed.',
        null=True,
    )

    procedure = MarkupField(
        blank=True,
        help_text='Enter details of how the system maintenance was performed.',
        null=True,
    )

    problems = MarkupField(
        blank=True,
        help_text='Describe problems that arose during system maintenance.',
        null=True,
    )

    referenced_records = models.ManyToManyField(
        'self',
        related_name='referencing_records',
        symmetrical=False,
        through='MaintenanceRecordRelationship',
    )

    documentation_records = models.ManyToManyField(
        'DocumentationRecord',
        blank=True,
        help_text='Select documentation relevant to this system maintenance.<br>',
        related_name='maintenance_records',
    )

    status = models.CharField(
        choices = STATUS_CHOICES,
        default='In Progress',
        help_text='What is the current status of the system maintenance?',
        max_length=15,
    )

    datetime = models.DateTimeField(
        'maintenance date/time',
        default=timezone.now,
        help_text='Specify the date/time that the system maintenance was '
                  'performed.',
    )

    class Meta:
        ordering = ['-datetime']
        verbose_name = 'maintenance record'
        verbose_name_plural = 'maintenance records'

    def __str__(self):
        return '{} - {} ({})'.format(
            self.system, self.maintenance_type, self.datetime.date())


class MaintenanceRecordRelationship(models.Model):

    referencing_record = models.ForeignKey(
        'MaintenanceRecord',
        related_name='referencing_record',
        on_delete=models.CASCADE,
    )

    referenced_record = models.ForeignKey(
        'MaintenanceRecord',
        related_name='referenced_record',
        on_delete=models.CASCADE,
    )

    class Meta:
        ordering = ['referencing_record']
        unique_together = ('referencing_record', 'referenced_record')

    def clean(self):
        if self.referencing_record == self.referenced_record:
            raise ValidationError('A record cannot by related to itself.')

    def __str__(self):
        return '{} ➤ {}'.format(
            self.referencing_record, self.referenced_record)


class MaintenanceType(models.Model):

    maintenance_type = models.CharField(
        help_text="Enter a type of maintenance "
                  "(e.g., 'Software Installation').",
        max_length=255,
        unique=True,
    )

    description = models.TextField(
        blank=True,
        help_text='Enter a description of the maintenance type.',
    )

    class Meta:
        ordering = ['maintenance_type']

    def __str__(self):
        return self.maintenance_type


class Software(models.Model):

    name = models.CharField(
        max_length=255,
        help_text="Enter the software's name.",
        unique=True,
    )

    class Meta:
        ordering = ['name']
        verbose_name = 'software package'
        verbose_name_plural = 'software packages'

    def __str__(self):
        return self.name


class SysAdmin(models.Model):

    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        help_text='Select a user.',
        on_delete=models.PROTECT,
        unique=True,
    )

    class Meta:
        verbose_name = 'system administrator'
        verbose_name_plural = 'system administrators'

    def __str__(self):
        if self.user.first_name or self.user.last_name:
            return '{} ({})'.format(
                ' '.join([self.user.first_name, self.user.last_name]),
                self.user.username)
        else:
            return self.user.username


class System(models.Model):

    name = models.CharField(
        'system name',
        help_text='Enter a brief, unique identifier for the system.',
        max_length=255,
        unique=True,
    )

    description = models.TextField(
        blank=True,
        help_text='Enter a description of the system.',
    )

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

devices/views.py
from django.http import Http404
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import DetailView, ListView

from .devices_settings import SYSTEM_MAINTENANCE_PAGINATE_BY
from .models import (Profile, DocumentationRecord, Hardware, MaintenanceRecord,
    MaintenanceType, Software, SysAdmin, System)

# Create your views here.

@login_required(login_url='/accounts/login/')
def profile(request,id):
    '''	
    View function to display the profile of the logged in user when they click on the user icon	
    '''
    current_user = request.user

    try:

        single_profile = Profile.objects.get(user=current_user.id)

        title = f'{current_user.username}\'s'

        return render(request, 'all-devices/my_profile.html', {"title":title,"single_profile":single_profile,"current_user":current_user})

    except ObjectDoesNotExist:
        raise Http404()

def sysadmin_check(user):
    """
    Check whether user is a sysadmin and has an active account.
    """

    return user.is_active and hasattr(user, 'sysadmin')

class SysAdminRequiredMixin(object):
    """
    Checks whether user is a sysadmin and has an active account.
    """

    @method_decorator(user_passes_test(
        sysadmin_check,
        login_url='/accounts/login/'))
    def dispatch(self, *args, **kwargs):
        return super(SysAdminRequiredMixin, self).dispatch(*args, **kwargs)
    

@login_required(login_url='/accounts/login/')
# @user_passes_test(sysadmin_check)
def home_view(request):
    '''
    View function to display the home page
    '''

    context = {
        'documentation_record_count':
            DocumentationRecord.objects.all().count(),
        'hardware_count': Hardware.objects.all().count(),
        'maintenance_record_count': MaintenanceRecord.objects.all().count(),
        'maintenance_type_count': MaintenanceType.objects.all().count(),
        'software_count': Software.objects.all().count(),
        'sys_admin_count': SysAdmin.objects.all().count(),
        'system_count': System.objects.all().count(),
    }
    return render(request, 'all-devices/home.html', context)

class MaintenanceRecordDetailView(DetailView):

    model = MaintenanceRecord
    template_name = 'all-devices/maintenance_record_detail.html'

class MaintenanceRecordListView(ListView):

    model = MaintenanceRecord
    paginate_by = SYSTEM_MAINTENANCE_PAGINATE_BY
    template_name = 'all-devices/maintenance_record_list.html'

class DocumentationRecordDetailView(DetailView):

    model = DocumentationRecord
    template_name = 'all-devices/documentation_record_detail.html'


class DocumentationRecordListView(ListView):

    model = DocumentationRecord
    paginate_by = SYSTEM_MAINTENANCE_PAGINATE_BY
    template_name = 'all-devices/documentation_record_list.html'

devices/templates/all-devices/base.html
{% load bootstrap4 %}
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">

    {% if title %}
    <title>MaintainIt - {{title}}</title>
    {% else %}
      <title> MaintainIt </title>
    {% endif %}

    <link rel="stylesheet" type="text/css" href="{% static 'markupfield_helpers/css/syntax-highlighting.css' %}">
    
    {% block styles %}
        {% bootstrap_css %}
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% endblock %}

</head>
<body>
    {% include "navbar.html" %}

    {% block content %}{%endblock%}

    {% block scripts %}
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    {% bootstrap_javascript %}
    {% endblock %}

</body>
</html>

devices/templates/all-devices/documentation_list_record_item.html
<a href="{% url 'devices:documentation_record_detail' record.id %}" class="list-group-item">
    <h5>
      {{ record.title }}
      <small>
        - {{ record.maintenance_type }}
        <br>Created: {{ record.created_at }}
        {% if record.created_at|date:'r' != record.updated_at|date:'r' %}
          <br>Updated: {{ record.updated_at }}
        {% endif %}
      </small>
    </h5>
  </a>

devices/templates/all-devices/documentation_record_detail.html
{% extends "all-devices/base.html" %}
{% load project_home %}

{% block title %}{{ object.title }}{% endblock %}

{% block content %}
  <div class='container'>

    <ol class="breadcrumb">
      {% project_home_breadcrumb_bs4 ' '%}
      <li class="breadcrumb-item" aria-label="breadcrumb" ><a href="{% url 'devices:home' %}">System Maintenance</a></li>
      <li class="breadcrumb-item" aria-label="breadcrumb">Documentation Records</li>
      <li class="breadcrumb-item active" aria-label="breadcrumb">{{ object }}</li>
    </ol>

    <a name='summary'></a>
    <div class="jumbotron">
      <h1>{{ object.title }}</h1>
      <p><strong>Type:</strong> {{ object.maintenance_type }}</p>
      <p><strong>Created:</strong> {{ object.created_at }}</p>
      {% if object.created_at|date:'r' != object.updated_at|date:'r' %}
        <p><strong>Updated:</strong> {{ object.updated_at }}</p>
      {% endif %}

      {% if object.documentation.raw %}
        <a class="btn btn-info btn-lg full-width-on-mobile" href="#documentation" role="button">Documentation</a>
      {% endif %}

      {% include "all-devices/related_records_button.html" with label="Maintenance Record" record_count=object.maintenance_records.count anchor="maintenance-records" singular_suffix="" plural_suffix="s" %}

    </div>

    {% if object.documentation.raw %}
      {% with type_of_record='documentation' record_pk=object.pk type_of_field='documentation' markup_type=object.documentation.markup_type panel_type='info' content=object.documentation %}
        {% include "all-devices/panel.html" %}
      {% endwith %}
    {% endif %}

    {% if object.maintenance_records.count %}
      <a name='maintenance-records'></a>
      <div class="panel panel-info">

        <div class="panel-heading">
          <h1 class="panel-title"><a href='#summary'>Related Maintenance Records</a></h1>
        </div>

        <div class="panel-body">

          <div class="list-group">
            {% for record in object.maintenance_records.all %}
              {% include "all-devices/_maintenance_record_list_item.html" %}
            {% endfor %}
          </div>

        </div>

        <a href='#maintenance-records'>
          <div class="panel-footer panel-info"></div>
        </a>

      </div>
    {% endif %}

  </div>
{% endblock content %}

devices/templates/all-devices/documentation_record_list.html
{% extends "all-devices/base.html" %}
{% load project_home %}

{% block title %}Documentation Records{% endblock %}

{% block content %}
  <div class='container'>

    <ol class="breadcrumb">
      {% project_home_breadcrumb_bs4 ' '%}
      <li class="breadcrumb-item" aria-label="breadcrumb" ><a href="{% url 'devices:home' %}">System Maintenance</a></li>
      <li class="breadcrumb-item active" aria-label="breadcrumb">Documentation Records</li>
    </ol>

    <div class="jumbotron">
      <h1>Documentation Records</h1>
    </div>

    <div class="list-group">
      {% for record in object_list %}
        {% include "all-devices/documentation_list_record_item.html" %}
      {% endfor %}
    </div>

    {% include "all-devices/pagination.html" %}

  </div>
{% endblock content %}

devices/templates/all-devices/home.html
{% extends 'all-devices/base.html' %}
{% load bootstrap4 %]
{% load static %}
{% load project_home %}

{% block styles%}
    {{block.super}}
    <link rel="stylesheet" href="{% static 'css/home.css'%}">
{% endblock %}

{% block content %}
  <div class="container">

    {% project_home_url as project_home_url %}
    {% if project_home_url %}
      <ol class="breadcrumb">
        {% project_home_breadcrumb_bs4 'Home_Label' %}   
        <li class="breadcrumb-item" aria-label="breadcrumb"><a href="{% url 'app:home' %}">Home</a></li>
          <li class=" breadcrumb-item active" aria-label="breadcrumb" aria-current="page">System Maintenance</li>
      </ol>
    {% endif %}

    <div class="jumbotron">

      <h1>System Maintenance</h1>
      <p>System maintenance records and other important system administration information is accessible via the buttons below.</p>

      {% if user.is_staff %}
        <p>
          To add or change system maintenance data, <span class="hide-on-mobile">click on the relevant <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span> or</span> go to the <a href="{% url 'admin:app_list' 'devices' %}" target="_blank">System Maintenance Admin Page</a>.
        </p>
      {% endif %}

      {% include "all-devices/summary_button.html" with label="Maintenance Record" btn_type="primary" list_count=maintenance_record_count list_url="devices:maintenance_record_list" singular_suffix="" plural_suffix="s" %}

      {% include "all-devices/summary_button.html" with label="Documentation Record" btn_type="primary" list_count=documentation_record_count list_url="devices:documentation_record_list" singular_suffix="" plural_suffix="s" %}

      {% include "all-devices/summary_button.html" with label="Hardware Type" btn_type="info" list_count=hardware_count list_url="" singular_suffix="" plural_suffix="s" %}

      {% include "all-devices/summary_button.html" with label="Maintenance Type" btn_type="info" list_count=maintenance_type_count list_url="" singular_suffix="" plural_suffix="s" %}

      {% include "all-devices/summary_button.html" with label="Software Package" btn_type="info" list_count=software_count list_url=""  singular_suffix="" plural_suffix="s" %}

      {% include "all-devices/summary_button.html" with label="System" btn_type="info" list_count=system_count list_url="" singular_suffix="" plural_suffix="s" %}

      {% include "all-devices/summary_button.html" with label="System Administrator" btn_type="info" list_count=sys_admin_count list_url="" singular_suffix="" plural_suffix="s" %}

    </div>
  </div>
{% endblock content %}

devices/templates/all-devices/maintenance_record_detail.html
{% extends "all-devices/base.html" %}
{% load project_home %}

{% block title %}{{ object.system }} {{ object.datetime|date:'Y-m-d' }}{% endblock %}

{% block content %}
  <div class='container'>

    <ol class="breadcrumb">
      {% project_home_breadcrumb_bs4 ' '%}
      <li class='breadcrumb-item' aria-label="breadcrumb"><a href="{% url 'devices:home' %}">Home</a></li>
      <li class='breadcrumb-item' aria-label="breadcrumb"><a href="{% url 'devices:maintenance_record_list' %}">Maintenance Records</a></li>
      <li class="breadcrumb-tiem active" aria-label="breadcrumb">{{ object }}</li>
    </ol>

    <a name='summary'></a>
    <div class="jumbotron
      {% if object.status == 'In Progress' %}alert-warning{% endif %}
      {% if object.status == 'Failed' %}alert-danger{% endif %}
    ">
      <h1>{{ object.system }} <small>{{ object.datetime.date }}</small></h1>
      <p><strong>Type:</strong> {{ object.maintenance_type }}</p>
      <p><strong>Who:</strong> {{ object.sys_admin }}</p>

      {% if object.hardware.count == 1 %}
        <p><strong>Hardware:</strong> {{ object.hardware.first }}</p>
      {% elif object.hardware.count > 1 %}
        <p><strong>Hardware:</strong></p>
        <ul>
          {% for hardware in object.hardware.all %}
            <li>{{ hardware }}</li>
          {% endfor %}
        </ul>
      {% endif %}

      {% if object.software.count == 1 %}
        <p><strong>Software:</strong> {{ object.software.first }}</p>
      {% elif object.software.count > 1 %}
        <p><strong>Software:</strong></p>
        <ul>
          {% for software in object.software.all %}
            <li>{{ software }}</li>
          {% endfor %}
        </ul>
      {% endif %}

      <p><strong>Status:</strong> {{ object.status }}</p>

      {% if object.description.raw %}
        <a class="btn btn-info btn-lg full-width-on-mobile" href="#description" role="button">Description</a>
      {% endif %}

      {% if object.procedure.raw %}
        <a class="btn btn-success btn-lg full-width-on-mobile" href="#procedure" role="button">Procedure</a>
      {% endif %}

      {% if object.problems.raw %}
        <a class="btn btn-danger btn-lg full-width-on-mobile" href="#problems" role="button">Problems</a>
      {% endif %}

      {% include "all-devices/related_records_button.html" with label="Related Document" record_count=object.documentation_records.count anchor="document-records" singular_suffix="" plural_suffix="s" %}

      {% include "all-devices/related_records_button.html" with label="Related Record" record_count=object.referenced_records.count|add:object.referencing_records.count anchor="related-records" singular_suffix="" plural_suffix="s" %}

      

    </div>

    {% if object.description.raw %}
      {% with type_of_record='maintenance' record_pk=object.pk type_of_field='description' markup_type=object.description.markup_type panel_type='info' content=object.description %}
        {% include "all-devices/panel.html" %}
      {% endwith %}
    {% endif %}

    {% if object.procedure.raw %}
      {% with type_of_record='maintenance' record_pk=object.pk type_of_field='procedure' markup_type=object.procedure.markup_type panel_type='success' content=object.procedure %}
        {% include "all-devices/panel.html" %}
      {% endwith %}
    {% endif %}

    {% if object.problems.raw %}
      {% with type_of_record='maintenance' record_pk=object.pk type_of_field='problems' markup_type=object.problems.markup_type panel_type='danger' content=object.problems %}
        {% include "all-devices/panel.html" %}
      {% endwith %}
    {% endif %}

    {% if object.documentation_records.count %}
      <a name='document-records'></a>
      <div class="panel panel-info">

        <div class="panel-heading">
          <h1 class="panel-title"><a href='#summary'>Relevant Documents</a></h1>
        </div>

        <div class="panel-body">
          <div class="list-group">
            {% for documentation in object.documentation_records.all %}

              <a href="{% url 'system_maintenance:documentation_record_detail' documentation.pk %}" class="list-group-item documentation-title">
                <h5>
                  {{ documentation.title }}
                  <small>- {{ documentation.category }}</small>
                  <br><small>Created: {{ documentation.created_at }}</small>
                  {% if documentation.created_at|date:'r' != documentation.updated_at|date:'r' %}
                    <br><small>Updated: {{ documentation.updated_at }}</small>
                  {% endif %}
                </h5>
              </a>

              <div class="list-group-item">
                <div class="container-fluid">
                  {{ documentation.documentation }}
                </div>
              </div>

            {% endfor %}
          </div>
        </div>

        <a href='#document-records'>
          <div class="panel-footer panel-info"></div>
        </a>

      </div>
    {% endif %}

    {% if object.referenced_records.count or object.referencing_records.count %}
      <a name='related-records'></a>
      <div class="panel panel-info">

        <div class="panel-heading">
          <h1 class="panel-title"><a href='#summary'>Related Records</a></h1>
        </div>

        <div class="panel-body">

          {% if object.referenced_records.count %}
            <h4>See also:</h4>
            <div class="list-group">
              {% for record in object.referenced_records.all %}
                {% include "all-devices/maintenance_record_list_item.html" %}
              {% endfor %}
            </div>
          {% endif %}

          {% if object.referencing_records.count %}
            <h4>Referenced by:</h4>
            <div class="list-group">
              {% for record in object.referencing_records.all %}
                {% include "all-devices/maintenance_record_list_item.html" %}
              {% endfor %}
            </div>
          {% endif %}

        </div>

        <a href='#related-records'>
          <div class="panel-footer panel-info"></div>
        </a>

      </div>
    {% endif %}

  </div>
{% endblock content %}

devices/templates/all-devices/maintenance_record_list.html
{% extends "all-devices/base.html" %}
{% load project_home %}

{% block title %}Maintenance Records{% endblock %}

{% block content %}
  <div class='container'>

    <ol class="breadcrumb">
        {% project_home_breadcrumb_bs4 ' '%}
        <li class="breadcrumb-item" aria-label="breadcrumb" ><a href="{% url 'devices:home' %}">System Maintenance</a></li>
        <li class="breadcrumb-item active" aria-label="breadcrumb">Maintenance Records</li>
      </ol>


    <div class="jumbotron">
      <h1>Maintenance Records</h1>
      <p>Background color indicates the status of the maintenance record:</p>
      <ul>
        <li>White: Complete</li>
        <li>Yellow: In Progress</li>
        <li>Red: Failed</li>
      </ul>
    </div>

    <div class="list-group">
      {% for record in object_list %}
        {% include "all-devices/maintenance_record_list_item.html" %}
      {% endfor %}
    </div>

    {% include "all-devices/pagination.html" %}

  </div>
{% endblock content %}

devices/templates/all-devices/maintenance_record_list_item.html
<a href="{% url 'devices:maintenance_record_detail' record.id %}" class="list-group-item
  {% if record.status == 'In Progress' %}list-group-item-warning{% endif %}
  {% if record.status == 'Failed' %}list-group-item-danger{% endif %}
">
    {{ record.datetime|date:'Y-m-d' }} - <strong>{{ record.system }}</strong> - {{ record.maintenance_type }} by {{ record.sys_admin }}

    {% if record.hardware.count %}
      - {{ record.hardware.all|join:', ' }}
    {% endif %}

    {% if record.software.count %}
      - {{ record.software.all|join:', ' }}
    {% endif %}
</a>

devices/templates/all-devices/pagination.html
{% if is_paginated %}
  <nav>
    <div class="text-center">
      <ul class="pagination">

        <li class="{% if not page_obj.has_previous %}disabled{% endif %}">
          <a href="{% if page_obj.has_previous %}?page=1{% endif %}">
            <span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span>
            <span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span>
          </a>
        </li>

        <li class="{% if not page_obj.has_previous %}disabled{% endif %}">
          <a href="{% if page_obj.has_previous %}?page={{ page_obj.previous_page_number }}{% endif %}">
            <span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span>
          </a>
        </li>

        <li class="disabled">
          <a>{{ page_obj.number }} / {{ page_obj.paginator.num_pages }}</a>
        </li>

        <li class="{% if not page_obj.has_next %}disabled{% endif %}">
          <a href="{% if page_obj.has_next %}?page={{ page_obj.next_page_number }}{% endif %}">
            <span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
          </a>
        </li>

        <li class="{% if not page_obj.has_next %}disabled{% endif %}">
          <a href="{% if page_obj.has_next %}?page={{ page_obj.paginator.num_pages }}{% endif %}">
            <span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
            <span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
          </a>
        </li>

      </ul>
    </div>
  </nav>
{% endif %}

devices/templates/all-devices/panel.html
<a name="{{ type_of_field }}"></a>
<div class="panel panel-{{ panel_type }}">

  <div class="panel-heading">
    <h1 class="panel-title">
      <a href='#summary'>{{ type_of_field|title }}</a>
      
    </h1>
  </div>

  <div class="panel-body">
    {{ content }}
  </div>

  <a href="#{{ type_of_field }}">
    <div class="panel-footer panel-{{ panel_type }}"></div>
  </a>

</div>

devices/templates/all-devices/related_records_button.html
{% if record_count %}
  {% with singular_suffix|add:","|add:plural_suffix as pluralize_rule %}
    <a class="btn btn-info btn-lg full-width-on-mobile" href="#{{ anchor }}" role="button">
      <span class="hide-on-mobile">{{ record_count }}</span>
      {{ label }}<span class="show-on-mobile-inline">{{ plural_suffix }}</span><span class="hide-on-mobile">{{ record_count|pluralize:pluralize_rule }}</span>
    </a>
  {% endwith %}
{% endif %}